# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-05 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataVIZ', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
    ]
