# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-07 08:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVIZ', '0003_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='exam1_marks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='exam2_marks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
